-- H2-compatible schema for lookup integration tests (BIGSERIAL -> IDENTITY)
-- 表名/列名加双引号，与 Spring Data JDBC 生成的 SQL 一致，避免 H2 MODE=PostgreSQL 下大小写不一致
CREATE TABLE IF NOT EXISTS "lookup_types" (
    "id"          BIGINT AUTO_INCREMENT PRIMARY KEY,
    "code"        VARCHAR(64) NOT NULL,
    "name"        VARCHAR(128),
    "description" VARCHAR(512),
    "create_time" TIMESTAMP,
    "update_time" TIMESTAMP,
    "create_by"   VARCHAR(64),
    "update_by"   VARCHAR(64),
    "deleted"     INT DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_lookup_types_code" ON "lookup_types" ("code");

-- value 为 H2 保留字，需加双引号
CREATE TABLE IF NOT EXISTS "lookup_items" (
    "id"                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    "lookup_type_id"      BIGINT NOT NULL,
    "lookup_types_key"    INT NOT NULL,
    "value"               VARCHAR(128) NOT NULL,
    "label"               VARCHAR(256),
    "sort_order"          INT DEFAULT 0,
    "create_time"     TIMESTAMP,
    "update_time"     TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INT DEFAULT 0,
    CONSTRAINT "fk_lookup_items_type" FOREIGN KEY ("lookup_type_id") REFERENCES "lookup_types" ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_lookup_items_type_value" ON "lookup_items" ("lookup_type_id", "value");

CREATE TABLE IF NOT EXISTS "system_users" (
    "id"           BIGINT AUTO_INCREMENT PRIMARY KEY,
    "username"     VARCHAR(64) NOT NULL,
    "display_name" VARCHAR(128) NOT NULL,
    "password"     VARCHAR(128) NOT NULL,
    "enabled"      BOOLEAN NOT NULL DEFAULT TRUE,
    "create_time"  TIMESTAMP,
    "update_time"  TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64),
    "deleted"      INT DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_users_username" ON "system_users" ("username");

CREATE TABLE IF NOT EXISTS "system_roles" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_key"     VARCHAR(64) NOT NULL,
    "role_name"    VARCHAR(128) NOT NULL,
    "enabled"      BOOLEAN NOT NULL DEFAULT TRUE,
    "create_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64),
    "deleted"      INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_roles_role_key" ON "system_roles" ("role_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_roles_role_name" ON "system_roles" ("role_name");

CREATE TABLE IF NOT EXISTS "system_user_roles" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      BIGINT NOT NULL,
    "role_id"      BIGINT NOT NULL,
    "create_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_user_roles_user_role" ON "system_user_roles" ("user_id", "role_id");
