-- H2-compatible schema for lookup integration tests (BIGSERIAL -> IDENTITY)
-- 表名/列名加双引号，与 Spring Data JDBC 生成的 SQL 一致，避免 H2 MODE=PostgreSQL 下大小写不一致
CREATE TABLE IF NOT EXISTS "lookup_types" (
    "id"          BIGINT AUTO_INCREMENT PRIMARY KEY,
    "code"        VARCHAR(64) NOT NULL,
    "name"        VARCHAR(128),
    "description" VARCHAR(512),
    "create_time" TIMESTAMP,
    "update_time" TIMESTAMP,
    "create_by"   VARCHAR(64),
    "update_by"   VARCHAR(64),
    "deleted"     INT DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_lookup_types_code" ON "lookup_types" ("code");

-- value 为 H2 保留字，需加双引号
CREATE TABLE IF NOT EXISTS "lookup_items" (
    "id"                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    "lookup_type_id"      BIGINT NOT NULL,
    "lookup_types_key"    INT NOT NULL,
    "value"               VARCHAR(128) NOT NULL,
    "label"               VARCHAR(256),
    "sort_order"          INT DEFAULT 0,
    "create_time"     TIMESTAMP,
    "update_time"     TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INT DEFAULT 0,
    CONSTRAINT "fk_lookup_items_type" FOREIGN KEY ("lookup_type_id") REFERENCES "lookup_types" ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_lookup_items_type_value" ON "lookup_items" ("lookup_type_id", "value");

CREATE TABLE IF NOT EXISTS "system_users" (
    "id"           BIGINT AUTO_INCREMENT PRIMARY KEY,
    "tenant_no"    VARCHAR(6) NOT NULL DEFAULT '000000',
    "username"     VARCHAR(64) NOT NULL,
    "display_name" VARCHAR(128) NOT NULL,
    "password"     VARCHAR(128) NOT NULL,
    "enabled"      BOOLEAN NOT NULL DEFAULT TRUE,
    "create_time"  TIMESTAMP,
    "update_time"  TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64),
    "deleted"      INT DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_users_username" ON "system_users" ("username");
CREATE INDEX IF NOT EXISTS "idx_system_users_tenant_no" ON "system_users" ("tenant_no");

CREATE TABLE IF NOT EXISTS "system_roles" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_key"     VARCHAR(64) NOT NULL,
    "role_name"    VARCHAR(128) NOT NULL,
    "enabled"      BOOLEAN NOT NULL DEFAULT TRUE,
    "create_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64),
    "deleted"      INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_roles_role_key" ON "system_roles" ("role_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_roles_role_name" ON "system_roles" ("role_name");

CREATE TABLE IF NOT EXISTS "system_user_roles" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      BIGINT NOT NULL,
    "role_id"      BIGINT NOT NULL,
    "create_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_user_roles_user_role" ON "system_user_roles" ("user_id", "role_id");

CREATE TABLE IF NOT EXISTS "system_menus" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id"       BIGINT NOT NULL DEFAULT 0,
    "menu_type"       VARCHAR(32) NOT NULL,
    "menu_name"       VARCHAR(128) NOT NULL,
    "sort_order"      INTEGER NOT NULL DEFAULT 0,
    "path"            VARCHAR(255),
    "component"       VARCHAR(255),
    "permission_code" VARCHAR(128),
    "visible"         BOOLEAN NOT NULL DEFAULT TRUE,
    "enabled"         BOOLEAN NOT NULL DEFAULT TRUE,
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_menus_parent_name" ON "system_menus" ("parent_id", "menu_name");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_menus_path" ON "system_menus" ("path");

CREATE TABLE IF NOT EXISTS "system_role_menus" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_id"      BIGINT NOT NULL,
    "menu_id"      BIGINT NOT NULL,
    "create_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"    VARCHAR(64),
    "update_by"    VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_role_menus_role_menu" ON "system_role_menus" ("role_id", "menu_id");

CREATE TABLE IF NOT EXISTS "system_configs" (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "config_name"      VARCHAR(128) NOT NULL,
    "config_key"       VARCHAR(128) NOT NULL,
    "config_value"     VARCHAR(1024) NOT NULL,
    "system_built_in"  BOOLEAN NOT NULL DEFAULT FALSE,
    "remarks"          VARCHAR(512),
    "create_time"      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"        VARCHAR(64),
    "update_by"        VARCHAR(64),
    "deleted"          INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_configs_key" ON "system_configs" ("config_key");

CREATE TABLE IF NOT EXISTS "system_notices" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notice_title"    VARCHAR(128) NOT NULL,
    "notice_type"     VARCHAR(32) NOT NULL,
    "notice_content"  CLOB NOT NULL,
    "status"          VARCHAR(32) NOT NULL,
    "remarks"         VARCHAR(512),
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "system_departments" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id"       BIGINT NOT NULL DEFAULT 0,
    "ancestors"       VARCHAR(512) NOT NULL DEFAULT '0',
    "dept_name"       VARCHAR(128) NOT NULL,
    "dept_category"   VARCHAR(32),
    "sort_order"      INTEGER NOT NULL DEFAULT 0,
    "leader_user_id"  BIGINT,
    "phone"           VARCHAR(32),
    "email"           VARCHAR(128),
    "status"          VARCHAR(32) NOT NULL,
    "remarks"         VARCHAR(512),
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_departments_parent_name"
    ON "system_departments" ("parent_id", "dept_name");

CREATE TABLE IF NOT EXISTS "system_posts" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dept_id"         BIGINT NOT NULL,
    "post_code"       VARCHAR(64) NOT NULL,
    "post_category"   VARCHAR(32),
    "post_name"       VARCHAR(128) NOT NULL,
    "sort_order"      INTEGER NOT NULL DEFAULT 0,
    "status"          VARCHAR(32) NOT NULL,
    "remarks"         VARCHAR(512),
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_posts_code" ON "system_posts" ("post_code");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_posts_dept_name" ON "system_posts" ("dept_id", "post_name");

CREATE TABLE IF NOT EXISTS "system_user_posts" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"         BIGINT NOT NULL,
    "post_id"         BIGINT NOT NULL,
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_user_posts_user_post"
    ON "system_user_posts" ("user_id", "post_id");

CREATE TABLE IF NOT EXISTS "system_tenant_packages" (
    "id"                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "package_name"           VARCHAR(128) NOT NULL,
    "menu_check_strictly"    BOOLEAN NOT NULL DEFAULT TRUE,
    "enabled"                BOOLEAN NOT NULL DEFAULT TRUE,
    "remarks"                VARCHAR(512),
    "create_time"            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"              VARCHAR(64),
    "update_by"              VARCHAR(64),
    "deleted"                INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_tenant_packages_name"
    ON "system_tenant_packages" ("package_name");

CREATE TABLE IF NOT EXISTS "system_tenant_package_menus" (
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "package_id"     BIGINT NOT NULL,
    "menu_id"        BIGINT NOT NULL,
    "create_time"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"      VARCHAR(64),
    "update_by"      VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_tenant_package_menus_package_menu"
    ON "system_tenant_package_menus" ("package_id", "menu_id");

CREATE TABLE IF NOT EXISTS "system_tenants" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_no"         VARCHAR(6) NOT NULL,
    "company_name"      VARCHAR(128) NOT NULL,
    "contact_name"      VARCHAR(64),
    "contact_phone"     VARCHAR(32),
    "social_credit_code" VARCHAR(64),
    "address"           VARCHAR(255),
    "domain"            VARCHAR(255),
    "intro"             VARCHAR(512),
    "package_id"        BIGINT,
    "expire_time"       TIMESTAMP,
    "user_limit"        INTEGER,
    "status"            VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    "remarks"           VARCHAR(512),
    "create_time"       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"         VARCHAR(64),
    "update_by"         VARCHAR(64),
    "deleted"           INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_tenants_tenant_no" ON "system_tenants" ("tenant_no");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_tenants_company_name" ON "system_tenants" ("company_name");

CREATE TABLE IF NOT EXISTS "system_clients" (
    "id"                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_id"               VARCHAR(64) NOT NULL,
    "client_key"              VARCHAR(64) NOT NULL,
    "client_secret"           VARCHAR(256) NOT NULL,
    "grant_types"             VARCHAR(256) NOT NULL,
    "device_type"             VARCHAR(32) NOT NULL,
    "active_timeout_seconds"  BIGINT NOT NULL,
    "fixed_timeout_seconds"   BIGINT NOT NULL,
    "status"                  VARCHAR(32) NOT NULL,
    "remarks"                 VARCHAR(512),
    "create_time"             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"               VARCHAR(64),
    "update_by"               VARCHAR(64),
    "deleted"                 INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_clients_client_id" ON "system_clients" ("client_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_system_clients_client_key" ON "system_clients" ("client_key");

CREATE TABLE IF NOT EXISTS "system_login_infos" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id"       VARCHAR(64) NOT NULL DEFAULT '000000',
    "username"        VARCHAR(64) NOT NULL,
    "client_id"       VARCHAR(64),
    "device_type"     VARCHAR(32),
    "ipaddr"          VARCHAR(128),
    "login_location"  VARCHAR(255),
    "browser"         VARCHAR(128),
    "os"              VARCHAR(128),
    "status"          VARCHAR(32) NOT NULL,
    "msg"             VARCHAR(512),
    "login_time"      TIMESTAMP NOT NULL,
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "idx_system_login_infos_username" ON "system_login_infos" ("username");
CREATE INDEX IF NOT EXISTS "idx_system_login_infos_login_time" ON "system_login_infos" ("login_time");
CREATE INDEX IF NOT EXISTS "idx_system_login_infos_status" ON "system_login_infos" ("status");

CREATE TABLE IF NOT EXISTS "system_oper_logs" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"           VARCHAR(128) NOT NULL,
    "business_type"   VARCHAR(32) NOT NULL,
    "method"          VARCHAR(255),
    "request_method"  VARCHAR(32),
    "operator_type"   VARCHAR(32) NOT NULL DEFAULT 'MANAGE',
    "oper_name"       VARCHAR(64) NOT NULL,
    "dept_name"       VARCHAR(128),
    "oper_url"        VARCHAR(512),
    "oper_ip"         VARCHAR(128),
    "oper_location"   VARCHAR(255),
    "oper_param"      CLOB,
    "json_result"     CLOB,
    "status"          VARCHAR(32) NOT NULL,
    "error_msg"       CLOB,
    "cost_time"       BIGINT NOT NULL DEFAULT 0,
    "oper_time"       TIMESTAMP NOT NULL,
    "create_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"       VARCHAR(64),
    "update_by"       VARCHAR(64),
    "deleted"         INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "idx_system_oper_logs_title" ON "system_oper_logs" ("title");
CREATE INDEX IF NOT EXISTS "idx_system_oper_logs_oper_time" ON "system_oper_logs" ("oper_time");
CREATE INDEX IF NOT EXISTS "idx_system_oper_logs_status" ON "system_oper_logs" ("status");
