CREATE TABLE IF NOT EXISTS "resource_oss_files" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "file_name"          VARCHAR(255) NOT NULL,
    "original_file_name" VARCHAR(255) NOT NULL,
    "suffix"             VARCHAR(64),
    "url"                VARCHAR(1024) NOT NULL,
    "uploader"           VARCHAR(64) NOT NULL,
    "provider"           VARCHAR(64) NOT NULL,
    "object_key"         VARCHAR(512) NOT NULL,
    "size_bytes"         BIGINT NOT NULL DEFAULT 0,
    "ext_json"           CLOB,
    "create_time"        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"          VARCHAR(64),
    "update_by"          VARCHAR(64),
    "deleted"            INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "idx_resource_oss_files_file_name"
    ON "resource_oss_files" ("file_name");

CREATE TABLE IF NOT EXISTS "resource_oss_configs" (
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "config_key"     VARCHAR(128) NOT NULL,
    "access_key"     VARCHAR(255) NOT NULL,
    "secret_key"     VARCHAR(255) NOT NULL,
    "bucket"         VARCHAR(255) NOT NULL,
    "prefix"         VARCHAR(255),
    "endpoint"       VARCHAR(512),
    "custom_domain"  VARCHAR(512),
    "https_enabled"  BOOLEAN NOT NULL DEFAULT TRUE,
    "region"         VARCHAR(128),
    "access_policy"  VARCHAR(64) NOT NULL DEFAULT 'PRIVATE',
    "status"         INTEGER NOT NULL DEFAULT 1,
    "default_flag"   INTEGER NOT NULL DEFAULT 0,
    "built_in"       INTEGER NOT NULL DEFAULT 0,
    "provider"       VARCHAR(64) NOT NULL,
    "ext_json"       CLOB,
    "create_time"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"      VARCHAR(64),
    "update_by"      VARCHAR(64),
    "deleted"        INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "uk_resource_oss_configs_key"
    ON "resource_oss_configs" ("config_key", "deleted");

CREATE INDEX IF NOT EXISTS "idx_resource_oss_configs_default"
    ON "resource_oss_configs" ("default_flag", "deleted");
