CREATE TABLE IF NOT EXISTS "resource_oss_files" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "file_name"          VARCHAR(255) NOT NULL,
    "original_file_name" VARCHAR(255) NOT NULL,
    "suffix"             VARCHAR(64),
    "url"                VARCHAR(1024) NOT NULL,
    "uploader"           VARCHAR(64) NOT NULL,
    "provider"           VARCHAR(64) NOT NULL,
    "object_key"         VARCHAR(512) NOT NULL,
    "size_bytes"         BIGINT NOT NULL DEFAULT 0,
    "ext_json"           CLOB,
    "create_time"        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "create_by"          VARCHAR(64),
    "update_by"          VARCHAR(64),
    "deleted"            INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "idx_resource_oss_files_file_name"
    ON "resource_oss_files" ("file_name");
