# syntax=docker/dockerfile:1.7

FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /workspace

COPY . .

RUN mvn -B -pl artemis-modules/artemis-system/artemis-system-start -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /workspace/artemis-modules/artemis-system/artemis-system-start/target/artemis-system-start-*.jar /app/app.jar

EXPOSE 9300

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
