ALTER TABLE system_menus
    ADD COLUMN IF NOT EXISTS query_param VARCHAR(512);

ALTER TABLE system_menus
    ADD COLUMN IF NOT EXISTS external_link BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE system_menus
    ADD COLUMN IF NOT EXISTS cacheable BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE system_menus
    ADD COLUMN IF NOT EXISTS icon VARCHAR(128);

ALTER TABLE system_menus
    ADD COLUMN IF NOT EXISTS remarks VARCHAR(512);
