CREATE TABLE resource_oss_configs (
    id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    config_key     VARCHAR(128) NOT NULL,
    access_key     VARCHAR(255) NOT NULL,
    secret_key     VARCHAR(255) NOT NULL,
    bucket         VARCHAR(255) NOT NULL,
    prefix         VARCHAR(255),
    endpoint       VARCHAR(512),
    custom_domain  VARCHAR(512),
    https_enabled  TINYINT(1) NOT NULL DEFAULT 1,
    region         VARCHAR(128),
    access_policy  VARCHAR(64) NOT NULL DEFAULT 'PRIVATE',
    status         TINYINT NOT NULL DEFAULT 1,
    default_flag   TINYINT NOT NULL DEFAULT 0,
    built_in       TINYINT NOT NULL DEFAULT 0,
    provider       VARCHAR(64) NOT NULL,
    ext_json       TEXT,
    create_time    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by      VARCHAR(64),
    update_by      VARCHAR(64),
    deleted        TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_resource_oss_configs_key (config_key, deleted),
    KEY idx_resource_oss_configs_default (default_flag, deleted)
);
