# Tomcat 配置
server:
  port: 9200

# Spring 配置
spring:
  application:
    name: artemis-auth
  profiles:
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:artemis-auth.yml
